nombre= input("ingrese su nombre y apellido: ")
edad= int(input("\nIngrese su edad: "))
carrera= input("\ningrese su carrera: ")
estatura= float(input("\ningrese su estatuda en decimales: "))
print("\n===== INFORMACION =====\n")
print(f"Nombre: {nombre}")
print(f"Edad: {edad}")
print(f"Carrera: {carrera}")
print(f"Estatura: {estatura}")
